### ISSUE TITLE
[config scratch] Debugging de LWC en consola - Session Settings

### ISSUE THREAD

**Issue by BrunoRicci** [sebastianclaros/teatime#29]
Deshabilitar Lightning Web Security para que permita hacer debug del código JS desde la consola de chrome.
Si está habilitado, todos los console.log generados por los LWC salen asociados a un mismo archivo "aura_prod.js" haciendo imposible saber de cuál componente proviene ese log, y abrirlo para debugear.

Ejemplo:

<img src="https://github.com/sebastianclaros/teatime/assets/50888603/8e330a15-3325-4470-9b32-f8b7df9c3472" width="400"/>

---
###

Se propone destildar la checkbox (colocar en **false**) para que los logs salgan asociados a sus respectivos archivos JS:

<img src="https://github.com/sebastianclaros/teatime/assets/50888603/69b02396-ec59-4e05-9ad9-a6b1a7ba0442" width="400"/>

---
Resultado:

<img src="https://github.com/sebastianclaros/teatime/assets/50888603/2b9a9efa-adcc-4a85-839e-af49d89b1a0c" width="400"/>

**Abriendo el archivo asociado al log**:

<img src="https://github.com/sebastianclaros/teatime/assets/50888603/7880be4d-ad81-464a-97da-f00df8544d74" width="400"/>

**Comment by sebastianclaros** [comment]
https://salesforcegraells.wordpress.com/lightning-web-security/
https://developer.salesforce.com/docs/platform/lwc/guide/security-lwsec-enable-scratch-orgs.html

”settings": {
     "securitySettings": {
         "sessionSettings": {
            "lockerServiceNext": false
           }
      }
}

**Comment by sebastianclaros** [comment]
Encontramos que no es necesario quitar el LWS para poder debuggear
